services:
  # ----------------------------------------------------
  # 1. SERVICIO WEB + PHP (Apache)
  # ----------------------------------------------------
  web:
    build:
      context: ./backend/php
    container_name: p-404rpm-apache
    restart: unless-stopped
    # Sin 'ports' porque solo se accede a trav√©s del proxy
    volumes:
      - ./backend/src:/var/www/html
      - ./frontend:/var/www/frontend
      - ./frontend/css:/var/www/html/public/css
      - ./frontend/js:/var/www/html/public/js
    depends_on:
      - db
    networks:
      - p-404rpm_network

  # ----------------------------------------------------
  # 2. BASE DE DATOS
  # ----------------------------------------------------
  db:
    image: mysql:8.0
    container_name: p-404rpm-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: 404rpm_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - p-404rpm_network

  # ----------------------------------------------------
  # 3. PHPMYADMIN
  # ----------------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: p-404rpm-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:81"
    environment:
      PMA_HOST: db
      PMA_PORT: 3307
    depends_on:
      - db
    networks:
      - p-404rpm_network

  # ----------------------------------------------------
  # 4. NODE
  # ----------------------------------------------------
  node:
    image: node:22
    container_name: p-404rpm-node
    working_dir: /var/www/html
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - "5174:5174"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - p-404rpm_network
    
  # ----------------------------------------------------
  # 5. PROXY
  # ----------------------------------------------------
  proxy:
    image: nginx:alpine
    container_name: p-404rpm-proxy
    restart: unless-stopped
    ports:
      - "81:81"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - p-404rpm_network

networks:
  p-404rpm_network:
    driver: bridge

volumes:
  dbdata: