services:
  # ----------------------------------------------------
  # 1. SERVICIO WEB + PHP (Apache)
  # ----------------------------------------------------
  web:
    build:
      context: ./backend/php
    container_name: 404rpm-apache
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend/src:/var/www/html
      - ./frontend:/var/www/frontend
      - ./frontend/css:/var/www/html/public/css
      - ./frontend/js:/var/www/html/public/js
    depends_on:
      - db
    networks:
      - 404rpm_network

  # ----------------------------------------------------
  # 2. BASE DE DATOS
  # ----------------------------------------------------
  db:
    image: mysql:8.0
    container_name: 404rpm-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: 404rpm_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - 404rpm_network

  # ----------------------------------------------------
  # 3. PHPMYADMIN
  # ----------------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 404rpm-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - 404rpm_network

  # ----------------------------------------------------
  # 4. NODE
  # ----------------------------------------------------
  node:
    image: node:22
    container_name: 404rpm-node
    working_dir: /var/www/html
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - 404rpm_network
    
    # ----------------------------------------------------
    # 5. PROXY
    # ----------------------------------------------------
    proxy:
        image: nginx:alpine
        container_name: 404rpm-proxy
        restart: unless-stopped
        ports:
        - "443:443"
        volumes:
        - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./certs/nginx-selfsigned.crt:/etc/nginx/localhost.crt
        - ./certs/nginx-selfsigned.key:/etc/nginx/localhost.key
        depends_on:
        - web1
        - web2

networks:
  404rpm_network:
    driver: bridge

volumes:
  dbdata: